N-dimensional array is an object, capable of holding data elements of the same type and of a fixed size in multiple dimensions. 

In [6]:
import numpy as np 

#Creation of a 1-D array of five elements,

x = np.array([1,3,5,7,9]) # using 'array' method
x

array([1, 3, 5, 7, 9])

In [7]:
type(x)

numpy.ndarray

In [8]:
#Creation of a 2-D array from a list of lists

y = np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

Ndarrays possess several noteworthy attributes, including:

    ndim: This attribute returns the number of dimensions of the array.
    shape: The shape attribute returns the shape of the array as a tuple.
    size: This attribute returns the total number of elements in the array.
    dtype: The dtype attribute returns the data type of each element in the array.
    itemsize: This attribute returns the size of each element in bytes.
    nbytes: The nbytes attribute returns the total number of bytes consumed by all elements in the array.

In [9]:
print(y.ndim)
print(y.shape)
print(y.size)
print(y.dtype)
print(y.itemsize)
print(y.nbytes)

2
(2, 3)
6
int32
4
24


NumPy offers support for a diverse range of data types, which are determined based on the number of bytes required by the data elements. It is possible to explicitly specify a data type by making use of the dtype argument


In [10]:
z = np.array([1,5,3,7,9],dtype='float64')

In [11]:
z

array([1., 5., 3., 7., 9.])

In [12]:
z.dtype

dtype('float64')

## Creation of NumPy Arrays 

There are several ways to create ndarrays in NumPy. Here are a few of them:

    Using Python built-in datatypes like lists or tuples.
    Using NumPy array creation methods such as ones, ones_like, zeros, and zeros_like.
    Utilizing NumPy's numeric sequence generators.
    Leveraging NumPy's random module.
    Reading data from a file and creating an ndarray.
By making use of these methods, one can create ndarrays with different shapes, sizes, and data types. This flexibility allows for efficient manipulation and computation of large amounts of numerical data in NumPy.

In [21]:
#Using Python built-in datatypes like lists or tuples.
list1 = [[1,2,3],[4,5,6],[7,8,9]]
arr1 = np.array(list1,dtype='int64')

In [22]:
arr1.dtype

dtype('int64')

In [23]:
arr1.shape

(3, 3)

In [24]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [25]:
#Using NumPy array creation methods such as ones, ones_like, zeros, and zeros_like.

#Using zeros method

arr2 = np.zeros(shape=(3,4))
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
#using full method

arr3 = np.full(shape=(4,3),fill_value=7.9)
print(arr3)

[[7.9 7.9 7.9]
 [7.9 7.9 7.9]
 [7.9 7.9 7.9]
 [7.9 7.9 7.9]]


In [28]:
#using Ones method

arr4 = np.ones(shape=(3,4))
print(arr4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [29]:
my_array = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])

#using ones_like , zeros_like

arr5 = np.zeros_like(my_array)
arr5

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
arr6 = np.ones_like(my_array)
arr6

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [31]:
# Generate a sequence of numbers from 0 to 9 with a step of 2

arr = np.arange(0, 10, 2)
print(arr) 

[0 2 4 6 8]


In [32]:
# Generate a sequence of 5 evenly spaced numbers from 0 to 10
arr = np.linspace(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [36]:
# Generate a sequence of 5 numbers spaced logarithmically between 1 and 1000
arr = np.logspace(0, 3, 5)
print(arr)  

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [34]:
# Generate a sequence of 5 random numbers between 0 and 1
arr = np.random.rand(5)
print(arr)  

[0.70965947 0.78543698 0.01682409 0.65672314 0.56470689]


In [35]:
# Generate a sequence of 5 random integers between 0 and 9
arr = np.random.randint(0, 10, 5)
print(arr)  

[6 8 7 2 4]


In [37]:
#Using NumPy's random module
#Random module of numpy is used to generate various random sequences. 

np.random.seed(100)

x = np.random.rand(5) #5 random numbers between 0 to 1
print(x)

[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886]


In [38]:
type(x)

numpy.ndarray

In [39]:
y = np.random.randint(10,100,5) #5 random numbers between 10 to 100
print(y)

[63 76 24 44 34]


In [40]:
z = np.random.choice(y, size=None, replace=True, p=None)
print(z)

34


In [41]:
z = np.random.choice(y, size=None, replace=True, p=None)
print(z)

44


In [42]:
z = np.random.choice(y, size=None, replace=True, p=None)
print(z)

34


In [43]:
z = np.random.choice(y, size=None, replace=True, p=None)
print(z)

24


In [44]:
x = np.random.randn(3) # Standard normal distribution 
 
print(x)

[-0.45802699  0.43516349 -0.58359505]


In [45]:
x = np.loadtxt('data.txt')
print(x)

[[88.25 93.45 72.6  90.9 ]
 [72.3  78.85 92.15 65.75]
 [90.5  92.45 89.25 94.5 ]]
