# Temperature Prediction

In [195]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [196]:
dataset = pd.read_csv('../Datasets/SzegedWeatherHistory.csv')

In [197]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Formatted Date            96453 non-null  object 
 1   Summary                   96453 non-null  object 
 2   Precip Type               95936 non-null  object 
 3   Temperature (C)           96453 non-null  float64
 4   Apparent Temperature (C)  96453 non-null  float64
 5   Humidity                  96453 non-null  float64
 6   Wind Speed (km/h)         96453 non-null  float64
 7   Wind Bearing (degrees)    96453 non-null  int64  
 8   Visibility (km)           96453 non-null  float64
 9   Loud Cover                96453 non-null  int64  
 10  Pressure (millibars)      96453 non-null  float64
 11  Daily Summary             96453 non-null  object 
dtypes: float64(6), int64(2), object(4)
memory usage: 8.8+ MB


In [198]:
dataset.head(10)

Formatted Date        Summary Precip Type  Temperature (C)  \
0  2006-04-01 00:00:00.000 +0200  Partly Cloudy        rain         9.472222   
1  2006-04-01 01:00:00.000 +0200  Partly Cloudy        rain         9.355556   
2  2006-04-01 02:00:00.000 +0200  Mostly Cloudy        rain         9.377778   
3  2006-04-01 03:00:00.000 +0200  Partly Cloudy        rain         8.288889   
4  2006-04-01 04:00:00.000 +0200  Mostly Cloudy        rain         8.755556   
5  2006-04-01 05:00:00.000 +0200  Partly Cloudy        rain         9.222222   
6  2006-04-01 06:00:00.000 +0200  Partly Cloudy        rain         7.733333   
7  2006-04-01 07:00:00.000 +0200  Partly Cloudy        rain         8.772222   
8  2006-04-01 08:00:00.000 +0200  Partly Cloudy        rain        10.822222   
9  2006-04-01 09:00:00.000 +0200  Partly Cloudy        rain        13.772222   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                  7.388889      0.89            14.1197   
1                  7.227778      0.86            14.2646   
2                  9.377778      0.89             3.9284   
3                  5.944444      0.83            14.1036   
4                  6.977778      0.83            11.0446   
5                  7.111111      0.85            13.9587   
6                  5.522222      0.95            12.3648   
7                  6.527778      0.89            14.1519   
8                 10.822222      0.82            11.3183   
9                 13.772222      0.72            12.5258   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                     251          15.8263           0               1015.13   
1                     259          15.8263           0               1015.63   
2                     204          14.9569           0               1015.94   
3                     269          15.8263           0               1016.41   
4                     259          15.8263           0               1016.51   
5                     258          14.9569           0               1016.66   
6                     259           9.9820           0               1016.72   
7                     260           9.9820           0               1016.84   
8                     259           9.9820           0               1017.37   
9                     279           9.9820           0               1017.22   

                       Daily Summary  
0  Partly cloudy throughout the day.  
1  Partly cloudy throughout the day.  
2  Partly cloudy throughout the day.  
3  Partly cloudy throughout the day.  
4  Partly cloudy throughout the day.  
5  Partly cloudy throughout the day.  
6  Partly cloudy throughout the day.  
7  Partly cloudy throughout the day.  
8  Partly cloudy throughout the day.  
9  Partly cloudy throughout the day.

In [199]:
dataset['Formatted Date'] = pd.to_datetime(dataset['Formatted Date'],utc=True)

In [200]:
dataset.head()

Formatted Date        Summary Precip Type  Temperature (C)  \
0 2006-03-31 22:00:00+00:00  Partly Cloudy        rain         9.472222   
1 2006-03-31 23:00:00+00:00  Partly Cloudy        rain         9.355556   
2 2006-04-01 00:00:00+00:00  Mostly Cloudy        rain         9.377778   
3 2006-04-01 01:00:00+00:00  Partly Cloudy        rain         8.288889   
4 2006-04-01 02:00:00+00:00  Mostly Cloudy        rain         8.755556   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                  7.388889      0.89            14.1197   
1                  7.227778      0.86            14.2646   
2                  9.377778      0.89             3.9284   
3                  5.944444      0.83            14.1036   
4                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                     251          15.8263           0               1015.13   
1                     259          15.8263           0               1015.63   
2                     204          14.9569           0               1015.94   
3                     269          15.8263           0               1016.41   
4                     259          15.8263           0               1016.51   

                       Daily Summary  
0  Partly cloudy throughout the day.  
1  Partly cloudy throughout the day.  
2  Partly cloudy throughout the day.  
3  Partly cloudy throughout the day.  
4  Partly cloudy throughout the day.

In [201]:
dataset['year'] = dataset['Formatted Date'].dt.year
dataset['month'] = dataset['Formatted Date'].dt.month
dataset['day'] = dataset['Formatted Date'].dt.day

In [202]:
dataset.head()

Formatted Date        Summary Precip Type  Temperature (C)  \
0 2006-03-31 22:00:00+00:00  Partly Cloudy        rain         9.472222   
1 2006-03-31 23:00:00+00:00  Partly Cloudy        rain         9.355556   
2 2006-04-01 00:00:00+00:00  Mostly Cloudy        rain         9.377778   
3 2006-04-01 01:00:00+00:00  Partly Cloudy        rain         8.288889   
4 2006-04-01 02:00:00+00:00  Mostly Cloudy        rain         8.755556   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                  7.388889      0.89            14.1197   
1                  7.227778      0.86            14.2646   
2                  9.377778      0.89             3.9284   
3                  5.944444      0.83            14.1036   
4                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                     251          15.8263           0               1015.13   
1                     259          15.8263           0               1015.63   
2                     204          14.9569           0               1015.94   
3                     269          15.8263           0               1016.41   
4                     259          15.8263           0               1016.51   

                       Daily Summary  year  month  day  
0  Partly cloudy throughout the day.  2006      3   31  
1  Partly cloudy throughout the day.  2006      3   31  
2  Partly cloudy throughout the day.  2006      4    1  
3  Partly cloudy throughout the day.  2006      4    1  
4  Partly cloudy throughout the day.  2006      4    1

In [203]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype              
---  ------                    --------------  -----              
 0   Formatted Date            96453 non-null  datetime64[ns, UTC]
 1   Summary                   96453 non-null  object             
 2   Precip Type               95936 non-null  object             
 3   Temperature (C)           96453 non-null  float64            
 4   Apparent Temperature (C)  96453 non-null  float64            
 5   Humidity                  96453 non-null  float64            
 6   Wind Speed (km/h)         96453 non-null  float64            
 7   Wind Bearing (degrees)    96453 non-null  int64              
 8   Visibility (km)           96453 non-null  float64            
 9   Loud Cover                96453 non-null  int64              
 10  Pressure (millibars)      96453 non-null  float64            
 11  Daily Summary  

In [204]:
dataset.describe()

Temperature (C)  Apparent Temperature (C)      Humidity  \
count     96453.000000              96453.000000  96453.000000   
mean         11.932678                 10.855029      0.734899   
std           9.551546                 10.696847      0.195473   
min         -21.822222                -27.716667      0.000000   
25%           4.688889                  2.311111      0.600000   
50%          12.000000                 12.000000      0.780000   
75%          18.838889                 18.838889      0.890000   
max          39.905556                 39.344444      1.000000   

       Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
count       96453.000000            96453.000000     96453.000000     96453.0   
mean           10.810640              187.509232        10.347325         0.0   
std             6.913571              107.383428         4.192123         0.0   
min             0.000000                0.000000         0.000000         0.0   
25%             5.828200              116.000000         8.339800         0.0   
50%             9.965900              180.000000        10.046400         0.0   
75%            14.135800              290.000000        14.812000         0.0   
max            63.852600              359.000000        16.100000         0.0   

       Pressure (millibars)         year         month           day  
count          96453.000000  96453.00000  96453.000000  96453.000000  
mean            1003.235956   2011.00029      6.523001     15.727100  
std              116.969906      3.16216      3.448501      8.802216  
min                0.000000   2005.00000      1.000000      1.000000  
25%             1011.900000   2008.00000      4.000000      8.000000  
50%             1016.450000   2011.00000      7.000000     16.000000  
75%             1021.090000   2014.00000     10.000000     23.000000  
max             1046.380000   2016.00000     12.000000     31.000000

In [205]:
del dataset['Loud Cover']

In [206]:
X = dataset.drop(['Daily Summary', 'Formatted Date'], axis=1)
y = dataset['Daily Summary']

In [207]:
X

Summary Precip Type  Temperature (C)  Apparent Temperature (C)  \
0      Partly Cloudy        rain         9.472222                  7.388889   
1      Partly Cloudy        rain         9.355556                  7.227778   
2      Mostly Cloudy        rain         9.377778                  9.377778   
3      Partly Cloudy        rain         8.288889                  5.944444   
4      Mostly Cloudy        rain         8.755556                  6.977778   
...              ...         ...              ...                       ...   
96448  Partly Cloudy        rain        26.016667                 26.016667   
96449  Partly Cloudy        rain        24.583333                 24.583333   
96450  Partly Cloudy        rain        22.038889                 22.038889   
96451  Partly Cloudy        rain        21.522222                 21.522222   
96452  Partly Cloudy        rain        20.438889                 20.438889   

       Humidity  Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  \
0          0.89            14.1197                     251          15.8263   
1          0.86            14.2646                     259          15.8263   
2          0.89             3.9284                     204          14.9569   
3          0.83            14.1036                     269          15.8263   
4          0.83            11.0446                     259          15.8263   
...         ...                ...                     ...              ...   
96448      0.43            10.9963                      31          16.1000   
96449      0.48            10.0947                      20          15.5526   
96450      0.56             8.9838                      30          16.1000   
96451      0.60            10.5294                      20          16.1000   
96452      0.61             5.8765                      39          15.5204   

       Pressure (millibars)  year  month  day  
0                   1015.13  2006      3   31  
1                   1015.63  2006      3   31  
2                   1015.94  2006      4    1  
3                   1016.41  2006      4    1  
4                   1016.51  2006      4    1  
...                     ...   ...    ...  ...  
96448               1014.36  2016      9    9  
96449               1015.16  2016      9    9  
96450               1015.66  2016      9    9  
96451               1015.95  2016      9    9  
96452               1016.16  2016      9    9  

[96453 rows x 12 columns]

In [208]:
y

0             Partly cloudy throughout the day.
1             Partly cloudy throughout the day.
2             Partly cloudy throughout the day.
3             Partly cloudy throughout the day.
4             Partly cloudy throughout the day.
                          ...                  
96448    Partly cloudy starting in the morning.
96449    Partly cloudy starting in the morning.
96450    Partly cloudy starting in the morning.
96451    Partly cloudy starting in the morning.
96452    Partly cloudy starting in the morning.
Name: Daily Summary, Length: 96453, dtype: object

In [209]:
from sklearn.preprocessing  import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [210]:
categorical_indices = [0, 1]

In [211]:
ct = ColumnTransformer(
    transformers = [('encoder',OneHotEncoder(),categorical_indices)],
    remainder = 'passthrough'
)

In [212]:
X_transform = np.array(ct.fit_transform(X))

In [213]:
print(X_transform)

[[0.000e+00 0.000e+00 0.000e+00 ... 2.006e+03 3.000e+00 3.100e+01]
 [0.000e+00 0.000e+00 0.000e+00 ... 2.006e+03 3.000e+00 3.100e+01]
 [0.000e+00 0.000e+00 0.000e+00 ... 2.006e+03 4.000e+00 1.000e+00]
 ...
 [0.000e+00 0.000e+00 0.000e+00 ... 2.016e+03 9.000e+00 9.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 ... 2.016e+03 9.000e+00 9.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 ... 2.016e+03 9.000e+00 9.000e+00]]


In [214]:
from sklearn.model_selection import train_test_split

In [215]:
X_train,X_test,y_train,y_test = train_test_split(X_transform,y,test_size=0.2,random_state=1)

In [216]:
from sklearn.linear_model import LinearRegression

In [217]:
regressor = LinearRegression()

In [218]:
regressor.fit(X_train,y_train)

ValueError: could not convert string to float: 'Mostly cloudy throughout the day.'

In [220]:
from sklearn.linear_model import LogisticRegression

In [235]:
classifier = LogisticRegression()

In [223]:
classifier.fit(X_train,y_train)

M:\Software_Installed\Software_Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [226]:
y_pred = classifier.predict(X_test)

In [227]:
y_pred

array(['Mostly cloudy throughout the day.',
       'Mostly cloudy throughout the day.',
       'Mostly cloudy throughout the day.', ...,
       'Mostly cloudy throughout the day.',
       'Mostly cloudy throughout the day.',
       'Mostly cloudy throughout the day.'], dtype=object)

In [228]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [230]:
confusion_matrix(y_test,y_pred)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [231]:
accuracy_score(y_test,y_pred)

0.21357109532942822

In [233]:
from sklearn.neighbors import KNeighborsClassifier

In [234]:
KNN_classifier = KNeighborsClassifier(n_neighbors = 5)

In [237]:
KNN_classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [238]:
y_pred = KNN_classifier.predict(X_test)

In [239]:
accuracy_score(y_test,y_pred)

0.39090767715515007

In [240]:
dataset.head()

Formatted Date        Summary Precip Type  Temperature (C)  \
0 2006-03-31 22:00:00+00:00  Partly Cloudy        rain         9.472222   
1 2006-03-31 23:00:00+00:00  Partly Cloudy        rain         9.355556   
2 2006-04-01 00:00:00+00:00  Mostly Cloudy        rain         9.377778   
3 2006-04-01 01:00:00+00:00  Partly Cloudy        rain         8.288889   
4 2006-04-01 02:00:00+00:00  Mostly Cloudy        rain         8.755556   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                  7.388889      0.89            14.1197   
1                  7.227778      0.86            14.2646   
2                  9.377778      0.89             3.9284   
3                  5.944444      0.83            14.1036   
4                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Pressure (millibars)  \
0                     251          15.8263               1015.13   
1                     259          15.8263               1015.63   
2                     204          14.9569               1015.94   
3                     269          15.8263               1016.41   
4                     259          15.8263               1016.51   

                       Daily Summary  year  month  day  
0  Partly cloudy throughout the day.  2006      3   31  
1  Partly cloudy throughout the day.  2006      3   31  
2  Partly cloudy throughout the day.  2006      4    1  
3  Partly cloudy throughout the day.  2006      4    1  
4  Partly cloudy throughout the day.  2006      4    1

In [241]:
dataset.describe()

Temperature (C)  Apparent Temperature (C)      Humidity  \
count     96453.000000              96453.000000  96453.000000   
mean         11.932678                 10.855029      0.734899   
std           9.551546                 10.696847      0.195473   
min         -21.822222                -27.716667      0.000000   
25%           4.688889                  2.311111      0.600000   
50%          12.000000                 12.000000      0.780000   
75%          18.838889                 18.838889      0.890000   
max          39.905556                 39.344444      1.000000   

       Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  \
count       96453.000000            96453.000000     96453.000000   
mean           10.810640              187.509232        10.347325   
std             6.913571              107.383428         4.192123   
min             0.000000                0.000000         0.000000   
25%             5.828200              116.000000         8.339800   
50%             9.965900              180.000000        10.046400   
75%            14.135800              290.000000        14.812000   
max            63.852600              359.000000        16.100000   

       Pressure (millibars)         year         month           day  
count          96453.000000  96453.00000  96453.000000  96453.000000  
mean            1003.235956   2011.00029      6.523001     15.727100  
std              116.969906      3.16216      3.448501      8.802216  
min                0.000000   2005.00000      1.000000      1.000000  
25%             1011.900000   2008.00000      4.000000      8.000000  
50%             1016.450000   2011.00000      7.000000     16.000000  
75%             1021.090000   2014.00000     10.000000     23.000000  
max             1046.380000   2016.00000     12.000000     31.000000

In [243]:
X=dataset.iloc[:,4:10]
y=dataset.iloc[:,3]

In [244]:
X

Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                      7.388889      0.89            14.1197   
1                      7.227778      0.86            14.2646   
2                      9.377778      0.89             3.9284   
3                      5.944444      0.83            14.1036   
4                      6.977778      0.83            11.0446   
...                         ...       ...                ...   
96448                 26.016667      0.43            10.9963   
96449                 24.583333      0.48            10.0947   
96450                 22.038889      0.56             8.9838   
96451                 21.522222      0.60            10.5294   
96452                 20.438889      0.61             5.8765   

       Wind Bearing (degrees)  Visibility (km)  Pressure (millibars)  
0                         251          15.8263               1015.13  
1                         259          15.8263               1015.63  
2                         204          14.9569               1015.94  
3                         269          15.8263               1016.41  
4                         259          15.8263               1016.51  
...                       ...              ...                   ...  
96448                      31          16.1000               1014.36  
96449                      20          15.5526               1015.16  
96450                      30          16.1000               1015.66  
96451                      20          16.1000               1015.95  
96452                      39          15.5204               1016.16  

[96453 rows x 6 columns]

In [245]:
y

0         9.472222
1         9.355556
2         9.377778
3         8.288889
4         8.755556
           ...    
96448    26.016667
96449    24.583333
96450    22.038889
96451    21.522222
96452    20.438889
Name: Temperature (C), Length: 96453, dtype: float64